import React from 'react';

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Editor from './editor';
import Viewer from './viewer';

export default function Home() {
  const [editorState, setEditorState] = React.useState();
  const [isEditing, setIsEditing] = React.useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ backgroundColor: '#404040', color: '#EEFFEE', height: '2rem', fontSize: '1.2rem', display: 'flex', alignItems: 'center', paddingLeft: '1rem' }}>
          <div onClick={() => setIsEditing(!isEditing)}>{ isEditing ? 'to viewer' : 'to editor' }</div>
        </div>
        { isEditing ? <Editor editorState={ editorState } setEditorState={ setEditorState } /> : <Viewer editorState={ editorState } /> }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
